/**
 * Operator Dashboard Cards Configuration
 * Carduri specifice pentru operator - 6 carduri filtrate
 */

import type { CardSpec } from '@admin-shared/config/dashboard.types';

export const OPERATOR_DASHBOARD_CARDS: CardSpec[] = [
  // ROW 1: Financial Overview - Operator Perspective
  {
    key: 'total_revenue',
    title: 'Venituri Totale',
    subtitle: 'Organizația mea',
    unit: 'GBP_pence',
    format: 'currency',
    priority: 1,
    windows: [
      'today',
      'yesterday',
      'this_week',
      'last_week',
      'this_month',
      'last_month',
      'this_year',
      'all',
    ],
    defaultWindow: 'this_month',
    field: 'total_revenue_pence',
    access: ['operator'],
  },
  {
    key: 'total_bookings',
    title: 'Rezervări Totale',
    subtitle: 'Organizația mea',
    unit: 'count',
    format: 'number',
    priority: 2,
    windows: [
      'today',
      'yesterday',
      'this_week',
      'last_week',
      'this_month',
      'last_month',
      'this_year',
      'all',
    ],
    defaultWindow: 'this_month',
    field: 'total_bookings',
    access: ['operator'],
  },
  {
    key: 'avg_booking_value',
    title: 'Valoare Medie Rezervare',
    subtitle: 'Per rezervare',
    unit: 'GBP_pence',
    format: 'currency',
    priority: 3,
    windows: [
      'today',
      'yesterday',
      'this_week',
      'last_week',
      'this_month',
      'last_month',
      'this_year',
      'all',
    ],
    defaultWindow: 'this_month',
    field: 'avg_booking_pence',
    access: ['operator'],
  },

  // ROW 2: Operations - Operator Specific
  {
    key: 'operator_earnings',
    title: 'Câștiguri după Comision',
    subtitle: 'Suma finală primită',
    unit: 'GBP_pence',
    format: 'currency',
    priority: 4,
    windows: ['this_week', 'last_week', 'this_month', 'last_month', 'this_year', 'all'],
    defaultWindow: 'this_month',
    field: 'operator_payout_pence',
    access: ['operator'],
  },
  {
    key: 'cancelled_bookings',
    title: 'Rezervări Anulate',
    subtitle: 'Anulări organizația mea',
    unit: 'count',
    format: 'number',
    priority: 5,
    windows: [
      'today',
      'yesterday',
      'this_week',
      'last_week',
      'this_month',
      'last_month',
      'this_year',
      'all',
    ],
    defaultWindow: 'this_month',
    field: 'cancelled_count',
    access: ['operator'],
  },
  {
    key: 'scheduled_bookings',
    title: 'Rezervări Programate',
    subtitle: 'Viitoare organizația mea',
    unit: 'count',
    format: 'number',
    priority: 6,
    windows: ['custom'],
    defaultWindow: 'custom',
    field: 'scheduled_count',
    access: ['operator'],
  },
];
