/**
 * Dashboard Cards Configuration
 * Card specifications for dashboard metrics
 */

import type { CardSpec } from './dashboard.types';

export const DASHBOARD_CARDS: CardSpec[] = [
  // ROW 1: Financial Overview
  {
    key: 'total_revenue',
    title: 'Total Revenue',
    subtitle: 'Selected period',
    unit: 'GBP_pence',
    format: 'currency',
    priority: 1,
    windows: [
      'today',
      'yesterday',
      'this_week',
      'last_week',
      'this_month',
      'last_month',
      'this_year',
      'all',
    ],
    defaultWindow: 'this_month',
    field: 'total_revenue_pence',
    access: ['admin', 'operator'],
  },
  {
    key: 'total_bookings',
    title: 'Total Bookings',
    subtitle: 'All statuses',
    unit: 'count',
    format: 'number',
    priority: 2,
    windows: [
      'today',
      'yesterday',
      'this_week',
      'last_week',
      'this_month',
      'last_month',
      'this_year',
      'all',
    ],
    defaultWindow: 'this_month',
    field: 'total_bookings',
    access: ['admin', 'operator'],
  },
  {
    key: 'avg_booking_value',
    title: 'Average Booking Value',
    subtitle: 'Per booking',
    unit: 'GBP_pence',
    format: 'currency',
    priority: 3,
    windows: [
      'today',
      'yesterday',
      'this_week',
      'last_week',
      'this_month',
      'last_month',
      'this_year',
      'all',
    ],
    defaultWindow: 'this_month',
    field: 'avg_booking_pence',
    access: ['admin', 'operator'],
  },
  {
    key: 'platform_commission',
    title: 'Platform Commission',
    subtitle: 'Our earnings',
    unit: 'GBP_pence',
    format: 'currency',
    priority: 4,
    windows: ['this_week', 'last_week', 'this_month', 'last_month', 'this_year', 'all'],
    defaultWindow: 'this_month',
    field: 'platform_commission_pence',
    access: ['admin'],
  },
  // ROW 2: Operations & Future
  {
    key: 'operator_payout',
    title: 'Operator Payout',
    subtitle: 'To be paid',
    unit: 'GBP_pence',
    format: 'currency',
    priority: 5,
    windows: ['this_week', 'last_week', 'this_month', 'last_month', 'this_year', 'all'],
    defaultWindow: 'this_month',
    field: 'operator_payout_pence',
    access: ['admin'],
  },
  {
    key: 'cancelled_bookings',
    title: 'Cancelled Bookings',
    subtitle: 'Cancellations',
    unit: 'count',
    format: 'number',
    priority: 6,
    windows: [
      'today',
      'yesterday',
      'this_week',
      'last_week',
      'this_month',
      'last_month',
      'this_year',
      'all',
    ],
    defaultWindow: 'this_month',
    field: 'cancelled_count',
    access: ['admin', 'operator'],
  },
  {
    key: 'refunds_total',
    title: 'Refunds',
    subtitle: 'Returned to customers',
    unit: 'GBP_pence',
    format: 'currency',
    priority: 7,
    windows: ['this_week', 'last_week', 'this_month', 'last_month', 'this_year', 'all'],
    defaultWindow: 'this_month',
    field: 'refunds_total_pence',
    fallback: { value_null: '£0.00', reason: 'no_data', tooltip: 'No refunds yet' },
    access: ['admin'],
  },
  {
    key: 'scheduled_bookings',
    title: 'Scheduled Bookings',
    subtitle: 'Upcoming',
    unit: 'count',
    format: 'number',
    priority: 8,
    windows: ['custom'],
    defaultWindow: 'custom',
    field: 'scheduled_count',
    access: ['admin', 'operator'],
  },
  // Operator-specific card
  {
    key: 'operator_earnings',
    title: 'Operator Earnings',
    subtitle: 'Your commission',
    unit: 'GBP_pence',
    format: 'currency',
    priority: 9,
    windows: ['this_week', 'last_week', 'this_month', 'last_month', 'this_year', 'all'],
    defaultWindow: 'this_month',
    field: 'operator_earnings_pence',
    access: ['operator'],
  },
];
